yuntijs/yunti-ui

- src/Breadcrumb/demos/index.tsx
- src/Breadcrumb/index.md
- src/Breadcrumb/index.tsx
- src/index.ts
feat: add Breadcrumb component
> feat: add Breadcrumb component

- src/Card/demos/Grid.tsx
- src/Card/demos/Meta.tsx
- src/Card/demos/Playground.tsx
- src/Card/demos/Tab.tsx
- src/Card/demos/index.tsx
- src/Card/index.md
- src/Card/index.tsx
- src/index.ts
> feat: add Card component

- src/Descriptions/demos/Playground.tsx
- src/Descriptions/demos/index.tsx
- src/Descriptions/index.md
- src/Descriptions/index.tsx
- src/Descriptions/style.ts
- src/index.ts
feat: add Descriptions component
> feat: add Descriptions component

- src/Descriptions/index.tsx
- src/Descriptions/style.ts
- src/Divider/demos/Playground.tsx
- src/Divider/demos/index.tsx
- src/Divider/index.md
- src/Divider/index.tsx
- src/Divider/style.ts
- src/index.ts
1. delete descriptions itemStyle props
2. add Divider component
> delete descriptions itemStyle props and add Divider Component

- src/Modal/demos/Method.tsx
- src/Modal/demos/Playground.tsx
- src/Modal/demos/index.tsx
- src/Modal/index.md
- src/Modal/index.tsx
- src/Modal/style.ts
- src/index.ts
> feat: add Modal component

- package.json
- pnpm-lock.yaml
- src/Table/demos/Playground.tsx
- src/Table/demos/index.tsx
- src/Table/index.md
- src/Table/index.tsx
- src/index.ts
> feat: add Table component

- src/ChatInputArea/demos/index.tsx
- src/ChatInputArea/desktop/ChatInputArea.tsx
- src/ChatInputArea/index.md
- src/ChatInputArea/index.tsx
- src/index.ts
> feat: ChatInputArea

- src/ChatItem/components/MessageContent.tsx
- src/ChatItem/demos/Alert.tsx
- src/ChatItem/demos/Tmarkdown.tsx
- src/ChatItem/demos/index.tsx
- src/ChatItem/index.tsx
- src/EditableMessage/demos/index.tsx
- src/EditableMessage/index.tsx
> fix: export ChatItem & EditableMessage

- package.json
- src/index.ts
> fix: export SpeechSynthesisTTS

- src/index.ts
> feat: export useSpeechRecognition

- package.json
- pnpm-lock.yaml
- src/ChatItem/index.tsx
- src/WaveformIcon/demos/index.tsx
- src/WaveformIcon/index.md
- src/WaveformIcon/index.tsx
- src/index.ts
> Add WaveformIcon

- src/ChatItem/index.tsx
- src/ChatItem/style.ts
> fix: chatItem去除block分块样式

- src/ChatItem/components/Actions.tsx
- src/ChatItem/demos/index.tsx
- src/ChatItem/index.tsx
> fix: chatItem Action

- package.json
- pnpm-lock.yaml
- src/ChatItem/demos/cMarkdown.tsx
- src/ChatItem/index.md
- src/ChatMarkdown/MarkdownElements/AntThinking/Component.tsx
- src/ChatMarkdown/MarkdownElements/AntThinking/index.tsx
- src/ChatMarkdown/MarkdownElements/AntThinking/rehypePlugin.test.ts
- src/ChatMarkdown/MarkdownElements/AntThinking/rehypePlugin.ts
- src/ChatMarkdown/MarkdownElements/index.ts
- src/ChatMarkdown/demos/chat.tsx
- src/ChatMarkdown/demos/customComponents.tsx
- src/ChatMarkdown/demos/customHighlight.tsx
- src/ChatMarkdown/demos/customPlugins.tsx
- src/ChatMarkdown/demos/data.ts
- src/ChatMarkdown/demos/index.tsx
- src/ChatMarkdown/demos/transformer.tsx
- src/ChatMarkdown/index.md
- src/ChatMarkdown/index.tsx
- src/EditableMessage/demos/index.tsx
- src/EditableMessage/index.tsx
- src/index.ts
> feat: chatMarkdown

- src/ChatMarkdown/MarkdownElements/AntThinking/Component.tsx
> fix: chatMarkdown fontsize

- src/ChatMarkdown/MarkdownElements/AntThinking/Component.tsx
- src/ChatMarkdown/utils.ts
> fix: chatMarkdown

- src/ChatMarkdown/MarkdownElements/AntThinking/Component.tsx
- src/ChatMarkdown/MarkdownElements/AntThinking/remarkPlugin.ts
> fix: bot对话

- src/ChatMarkdown/MarkdownElements/AntThinking/Component.tsx
> fix: bot 对话思考中

- src/ChatItem/index.tsx
- src/ChatItem/type.ts
> fix: add `affixation` prop to chatItem

- src/CodeEditor/demos/index.tsx
- src/CodeEditor/index.md
- src/CodeEditor/index.tsx
- src/CodeEditor/style.ts
- src/Highlighter/demos/Md.tsx
- src/Highlighter/index.md
- src/hooks/useHighlight.ts
- src/index.ts
- src/utils/platform.ts
> feat: CodeEditor

- src/MonacoEditor/base/helper.ts
- src/MonacoEditor/base/index.tsx
- src/MonacoEditor/demos/Playground.tsx
- src/MonacoEditor/demos/markdownEditor.tsx
- src/MonacoEditor/index.md
> feat: add onblur in MonacoEditor

- package.json
- pnpm-lock.yaml
- src/MonacoEditor/base/helper.ts
- src/MonacoEditor/base/index.tsx
- src/MonacoEditor/base/style.ts
- src/MonacoEditor/demos/markdownEditor.tsx
- src/MonacoEditor/index.tsx
> fix: markdown monacoEditor

- src/SelectCard/index.tsx
> fix: selectedCard

- src/ChatItem/demos/index.tsx
- src/ChatItem/index.tsx
- src/ChatItem/style.ts
- src/ChatItem/type.ts
> fix: hide avatar for ChatItem

- src/ChatItem/style.ts
> fix: ChatItem

- src/ChatItem/style.ts
> fix: the max width of ChatItem

- src/ChatItem/demos/index.tsx
- src/ChatItem/style.ts
> fix: background for user chatItem
